name: couple_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.20.3
  table_calendar: ^3.1.2
  animations: ^2.0.11
  audioplayers: ^5.2.1
  image: ^4.9.2
  google_maps_flutter: ^2.5.3
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.5.3
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: 13.3.0
  firebase_ai: ^3.11.0
  firebase_messaging: ^16.2.0
  device_preview: ^1.2.0
  flutter_card_swiper: ^7.2.0
  universal_html: ^2.2.4
  google_sign_in: ^6.2.2
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.0
  http: ^1.2.0
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  record: ^6.2.1
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.3
  auto_size_text: ^3.0.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  purchases_flutter: ^10.10.1
  confetti: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/idle.gif
    - assets/eating.gif
    - assets/showering.gif
    - assets/capybara_front_v2.png
    - assets/bunny_front_v2.png
    - assets/puppy_front_v2.png
    - assets/kitty_front_v2.png
    - assets/3d_hat.png
    - assets/3d_glasses.png
    - assets/3d_bow.png
    - assets/sounds/laughter.wav
    - assets/sounds/cute_noise.wav

dependency_overrides:
  geolocator_android: 4.6.1
  image_cropper_platform_interface: 7.1.0


